apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-demo-app
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: enterprise-demo-app
  template:
    metadata:
      labels:
        app: enterprise-demo-app
    spec:
      containers:
      - name: app
        image: your-registry/enterprise-demo-app:1.0.0
        ports:
        - containerPort: 4000
